version: "2"

services:
    
    flow-collection:
        extends:
            file: flow_dc/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - flow-dc.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-flow-dc
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"

    flow-collection1:
        extends:
            file: flow_dc1/app.yml
            service: app
        networks:
            internal:
                aliases:
                    - flow-dc.docker.local
        logging:
            driver: syslog
            options:
                tag: docker-flow-dc
        restart: unless-stopped
        depends_on:
            - "mqtt_broker"
 
networks:
     internal:
         name: shoestring-internal
