[constants]
    machine="Pipe_2"	#Name of the machine being monitored (can't have spaces)
    source="Overhead Tank"

[connection]
    pin = 6 # BCM number of the pin the sensor input connects to

[sensor_character]
    pitch = "G1"
    max_pressure = "1.75 MPa"
    min_flow = 2 #Liters/min
    max_flow = 50 #Liters/min
