{
 "title": "Sources",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source",
    "query": "from(bucket: \"shoestring_data_bucket\")\n  |> range(start: -30d)\n  |> keep(columns: [\"source\"])\n  |> distinct(column: \"source\")\n  |> filter(fn: (r) => r[\"source\"] != \"null\")\n  |> group()"
   },
   { "name": "bucket", "query": "shoestring_data_bucket" },
   { "name": "measurement", "query": "flow_status" }
  ]
 },
 "panels": [
  {
   "title": "Flow history from ${source}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flow_rate\")\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Instantaneous Flow from ${source}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"flow_rate\")\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> tail(n: 1)"
    }
   ]
  },
  {
   "title": "Average flow rate from ${source} in timeframe",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "litreh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flow_rate\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> group(columns: [\"_measurement\", \"_field\"])"
    }
   ]
  },
  {
   "title": "Total flow from ${source} in timeframe",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"flow\")\r\n  |> filter(fn: (r) => r[\"source\"] == \"${source}\")\r\n  |> group(columns: [\"_measurement\", \"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  }
 ]
}