[constants]
    machine="Pipe_1"	#Name of the machine being monitored (can't have spaces)
    source="Water Tanker"

[connection]
    pin = 17 # BCM number of the pin the sensor input connects to

[sensor_character]
    pitch = "G1/2"
    max_pressure = "1.75 MPa"
    min_flow = 1 #Liters/min
    max_flow = 30 #Liters/min
    